[project]
name = "jsonrpc-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "json-rpc>=1.15.0",
    "requests>=2.32.5",
    "werkzeug>=3.1.3",
]
